
name: tadbeerai
description: TadbeerAI — Content to Action Intelligence System. AISeekho2026 Hackathon · Team TadbeerAI

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # State management
  provider: ^6.1.2

  # File picking (PDF upload)
  file_picker: ^8.0.3

  # PDF export
  pdf: ^3.10.8
  printing: ^5.12.0

  # Share
  share_plus: ^9.0.0

  # Local storage (cache RSS feed)
  shared_preferences: ^2.2.3

  # Hive for local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # RSS parsing
  webfeed: ^0.7.0

  # URL launcher
  url_launcher: ^6.3.0

  # Icons
  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  flutter_animate: ^4.5.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.1.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.3
  google_fonts: ^6.2.1
  uuid: ^4.5.1

dependency_overrides:
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
