import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/hive_service.dart';

class LanguageProvider extends ChangeNotifier {
  String _language;

  LanguageProvider({String initialLanguage = 'en'}) : _language = initialLanguage;

  String get language => _language;

  bool get isUrdu => _language == 'ur';
  bool get isRomanUrdu => _language == 'roman_ur';
  bool get isEnglish => _language == 'en';

  Future<void> setLanguage(String lang) async {
    if (_language != lang) {
      _language = lang;
      await HiveService.saveLanguage(lang);
      notifyListeners();
    }
  }

  static const Map<String, String> _urduTranslations = {
    // Navigation / Headers
    'Feed': 'فیڈ',
    'Input': 'ان پٹ',
    'Alerts': 'الرٹس',
    'Proactive feed': 'پروایکٹو فیڈ',
    'Business alerts': 'کاروباری الرٹس',
    'Settings': 'ترتیبات',
    'Select Your Persona': 'اپنی شخصیت منتخب کریں',
    'Analysis result': 'تجزیہ کا نتیجہ',
    'Simulation result': 'سیمولیشن کا نتیجہ',
    'Alert Center': 'الرٹ سینٹر',
    'System Execution Logs': 'سسٹم ایگزیکیوشن لاگز',
    'Market Intelligence Alerts': 'مارکیٹ انٹیلیجنس الرٹس',
    'About': 'تفصیلات',
    'All': 'تمام',
    'Energy': 'توانائی',
    'Currency': 'کرنسی',
    'Stock Market': 'اسٹاک مارکیٹ',
    'Gold': 'سونا',
    'Logistics': 'لاجسٹکس',
    'Finance': 'مالیات',
    'Policy': 'پالیسی',
    'Trade': 'تجارت',
    'Supply Chain': 'سپلائی چین',
    
    // Settings Screen
    'Appearance': 'ظاہری شکل',
    'Theme Mode': 'تھیم موڈ',
    'Language': 'زبان',
    'Email alerts': 'ای میل الرٹس',
    'SMS alerts': 'ایس ایم ایس الرٹس',
    'Push notifications': 'پش نوٹیفکیشنز',
    'Alert Frequency': 'الرٹ کی فریکوئنسی',
    'Account & Security': 'اکاؤنٹ اور سیکیورٹی',
    'Email Address': 'ای میل ایڈریس',
    'Phone Number': 'فون نمبر',
    'Change Password': 'پاس ورڈ تبدیل کریں',
    'Logout': 'لاگ آؤٹ',
    'Delete Account': 'اکاؤنٹ حذف کریں',
    'Clear Local Data': 'مقامی ڈیٹا صاف کریں',
    'Upgrade to Account': 'اکاؤنٹ میں اپ گریڈ کریں',
    'Create Account': 'اکاؤنٹ بنائیں',
    'Register phone & email to unlock free SMS and email risk alerts.': 'مفت ایس ایم ایس اور ای میل الرٹس ان لاک کرنے کے لیے فون اور ای میل رجسٹر کریں۔',
    'Light': 'روشنی',
    'Dark': 'تاریک',
    'System': 'سسٹم',
    'Instant': 'فوری',
    'Daily digest': 'روزانہ کا خلاصہ',
    'Receive analysis reports': 'تجزیاتی رپورٹیں حاصل کریں',
    'Receive risk updates via SMS': 'ایس ایم ایس کے ذریعے خطرے کی اپ ڈیٹس حاصل کریں',
    'Get instant device alerts': 'فوری ڈیوائس الرٹس حاصل کریں',
    'Category:': 'شخصیت:',
    'Not Selected': 'منتخب نہیں کیا گیا',
    'Display Name': 'ظاہری نام',
    'City': 'شہر',
    'Cancel': 'منسوخ کریں',
    'Save': 'محفوظ کریں',
    'Alert Channels': 'الرٹ چینلز',
    'App Version: TadbeerAI v1.0.0': 'ایپ ورژن: TadbeerAI v1.0.0',
    'Built for AISeekho2026': 'AISeekho2026 کے لیے تیار کردہ',
    'Privacy Policy': 'رازداری کی پالیسی',
    'Terms of Service': 'سروس کی شرائط',
    'Guest User': 'مہمان صارف',
    
    // Onboarding / Persona
    'Help TadbeerAI tailor its intelligence feed to your personal situation.': 'اپنی ذاتی صورتحال کے مطابق انٹیلیجنس فیڈ کو ترتیب دینے میں مدد کریں۔',
    'Shop Owner': 'دکاندار',
    'Business Owner': 'کاروبار کا مالک',
    'Employee': 'ملازم',
    'Student': 'طالب علم',
    'Retail, inventory, and monthly shop revenues.': 'ریٹیل، انوینٹری، اور ماہانہ دکان کی آمدنی۔',
    'Turnover, employee count, and industry growth.': 'ٹرن اوور، ملازمین کی تعداد، اور صنعت کی ترقی۔',
    'Salaried sectors, company sizes, and income.': 'تنخواہ دار شعبے، کمپنی کے سائز، اور آمدنی۔',
    'University research, fields of study, and stipends.': 'یونیورسٹی ریسرچ، مطالعہ کے شعبے، اور وظائف۔',
    
    // News Feed Screen & Cards
    'Act now': 'فوری اقدام',
    'Act': 'اقدام',
    'High': 'اہم',
    'Medium': 'درمیانہ',
    'Low': 'کم',
    'No alerts right now': 'اس وقت کوئی الرٹس موجود نہیں ہیں',
    'Pull to refresh or paste your own news below': 'دوبارہ لوڈ کرنے کے لیے نیچے کھینچیں یا نیچے اپنی خبر پیسٹ کریں',
    'No alerts in': 'میں کوئی الرٹ نہیں ہے',
    'Shop Specific': 'صرف دکاندار کے لیے',
    'Business Specific': 'صرف کاروباری مالک کے لیے',
    'Employee Specific': 'صرف ملازم کے لیے',
    'Student Specific': 'صرف طالب علم کے لیے',
    'Personalized': 'ذاتی نوعیت کا',
    
    // Input Screen
    'Market Pulse Ingestion': 'مارکیٹ پلس ان پٹ',
    'Paste news article, URL, or type a custom scenario to analyse the impact on Pakistan\'s business sectors.': 'پاکستان کے کاروباری شعبوں پر اثرات کا تجزیہ کرنے کے لیے خبریں، یو آر ایل، یا اپنی مرضی کا منظرنامہ لکھیں۔',
    'English': 'انگریزی',
    'Urdu (Roman)': 'رومن اردو',
    'Urdu (Script)': 'اردو رسم الخط',
    'Analyze Scenario': 'منظر نامے کا تجزیہ کریں',
    
    // Analysis Screen
    'Key insight': 'اہم معلومات',
    'Confidence': 'اعتماد',
    'Confidence reason': 'اعتماد کی وجہ',
    'Impact analysis': 'اثرات کا تجزیہ',
    'Recommended actions': 'تجویز کردہ اقدامات',
    'Agent trace': 'ایجنٹ ٹریس',
    'Execute & notify users': 'عمل درآمد اور الرٹ بھیجیں',
    'Confidence Reason': 'اعتماد کی وجہ',
    
    // Simulation / Before After
    'State changes': 'تبدیلیوں کی حالت',
    'Delivery': 'ڈیلیوری',
    'Exec log': 'لاگ',
    'State diff': 'تبدیلیوں کا موازنہ',
    'Simulated SMS draft': 'ایس ایم ایس کا مسودہ',
    'Execution alerts sent via SMS, email, and push to registered users.': 'ایس ایم ایس، ای میل، اور پش نوٹیفکیشن کے ذریعے صارفین کو الرٹس بھیج دیے گئے ہیں۔',
    'View trace': 'ٹریس دیکھیں',
    'Export PDF': 'پی ڈی ایف ڈاؤن لوڈ کریں',
    'm ago': 'منٹ پہلے',
    'h ago': 'گھنٹے پہلے',
    'd ago': 'دن پہلے',
    'Updated': 'اپ ڈیٹ ہوا',
    'high-urgency alert requires action': 'اہم الرٹ پر اقدام درکار ہے',
    'high-urgency alerts require action': 'اہم الرٹس پر اقدام درکار ہے',
    'Text': 'متن',
    'PDF': 'پی ڈی ایف',
    'URL': 'یو آر ایل',
    'Paste news or report': 'خبر یا رپورٹ پیسٹ کریں',
    'Try a sample': 'مثال آزمائیں',
    'Browse news sources': 'خبروں کے ذرائع دیکھیں',
    'Paste news article, report, or policy update here...\n\nAlso supports: اردو میں خبر یہاں لکھیں یا Roman Urdu mein likh saktay hain': 'خبر، رپورٹ، یا پالیسی اپ ڈیٹ یہاں پیسٹ کریں...\n\nاردو میں خبر یہاں لکھیں یا Roman Urdu mein likh saktay hain',
    '⛽ Petrol hike': '⛽ پٹرول کی قیمتوں میں اضافہ',
    '💸 Rupee drop': '💸 روپے کی قدر میں کمی',
    '📉 Sales decline': '📉 فروخت میں کمی',
    '🚢 Port delay': '🚢 بندرگاہ پر تاخیر',
    'Upload report PDF': 'رپورٹ پی ڈی ایف اپ لوڈ کریں',
    'Tap to upload PDF': 'پی ڈی ایف اپ لوڈ کرنے کے لیے دبائیں',
    'Tap to change file': 'فائل تبدیل کرنے کے لیے دبائیں',
    'Max 10 MB · Sales, policy, logistics reports': 'زیادہ سے زیادہ 10 ایم بی · سیلز، پالیسی، لاجسٹکس رپورٹس',
    'Supported: Sales reports, policy documents, logistics summaries, financial statements': 'سپورٹڈ: سیلز رپورٹس، پالیسی دستاویزات، لاجسٹکس خلاصے، مالیاتی گوشوارے',
    'Paste a specific article URL': 'مخصوص مضمون کا یو آر ایل پیسٹ کریں',
    'Open a source, find an article, then copy & paste its URL above': 'مجموعہ کھولیں، مضمون تلاش کریں، پھر اس کا یو آر ایل کاپی کر کے اوپر پیسٹ کریں',
    'Paste the full URL of a specific news article — not a homepage. TadbeerAI will scrape and analyse the article content automatically.': 'مخصوص خبر کے مضمون کا مکمل یو آر ایل پیسٹ کریں — ہوم پیج نہیں۔ تدبیر اے آئی مضمون کو خودکار طریقے سے پڑھے گی اور تجزیہ کرے گی۔',
    'Paste from clipboard': 'کلپ بورڈ سے پیسٹ کریں',
    'Analyse with TadbeerAI': 'تدبیر اے آئی سے تجزیہ کریں',
    'Please paste some text first': 'براہ کرم پہلے کچھ متن پیسٹ کریں',
    'Please upload a PDF first': 'براہ کرم پہلے پی ڈی ایف اپ لوڈ کریں',
    'Please enter a URL first': 'براہ کرم پہلے یو آر ایل درج کریں',
    'URL must start with http:// or https://': 'یو آر ایل کا http:// یا https:// سے شروع ہونا ضروری ہے',
    'This looks like a homepage, not an article. Please paste a specific article URL.': 'یہ ہوم پیج لگتا ہے، مضمون نہیں۔ براہ کرم مخصوص مضمون کا یو آر ایل پیسٹ کریں۔',
    'Analysing…': 'تجزیہ جاری ہے…',
    'Done': 'مکمل',
    'Antigravity pipeline · 5 agents': 'اینٹی گریویٹی پائپ لائن · 5 ایجنٹس',
    'Running…': 'جاری ہے…',
    'Guest Mode Simulation': 'مہمان موڈ سیمولیشن',
    'You are running in Guest Mode. The simulation will execute and calculate results, but no real email or SMS alerts can be dispatched. Create an account to enable real-time alert notifications.': 'آپ مہمان موڈ میں چلا رہے ہیں۔ سیمولیشن چلے گی اور نتائج کا حساب لگائے گی، لیکن کوئی بھی حقیقی ای میل یا ایس ایم ایس الرٹ نہیں بھیجا جا سکتا۔ ریئل ٹائم نوٹیفکیشن حاصل کرنے کے لیے اکاؤنٹ بنائیں۔',
    'Run Simulation': 'سیمولیشن چلائیں',
    'Limited Notifications': 'محدود نوٹیفکیشنز',
    'Your profile isn\'t fully configured for notifications. The simulation will run, but real-time alerts (SMS, Email) won\'t be dispatched.\n\nGo to Settings to complete your profile for full notification support.': 'آپ کا پروفائل نوٹیفکیشنز کے لیے مکمل طور پر ترتیب نہیں دیا گیا ہے۔ سیمولیشن چلے گی، لیکن ریئل ٹائم الرٹس (ایس ایم ایس، ای میل) نہیں بھیجے جائیں گے۔\n\nمکمل نوٹیفکیشنز کے لیے ترتیبات میں جا کر اپنا پروفائل مکمل کریں۔',
    'Run Anyway': 'بہر حال چلائیں',
    'Something went wrong': 'کچھ غلط ہو گیا',
    'Retry': 'دوبارہ کوشش کریں',
    'Please try again': 'براہ کرم دوبارہ کوشش کریں',
    'Execution failed': 'عملدرآمد ناکام رہا',
    'TadbeerAI is thinking…': 'تدبیر اے آئی سوچ رہا ہے…',
    'Ingesting content…': 'مواد حاصل کیا جا رہا ہے…',
    'Extracting insights…': 'معلومات نکالی جا رہی ہیں…',
    'Analysing impact…': 'اثرات کا تجزیہ کیا جا رہا ہے…',
    'Generating actions…': 'اقدامات تجویز کیے جا رہے ہیں…',
    'Running simulation…': 'سیمولیشن چلائی جا رہی ہے…',
    'Alerts sent to': 'الرٹس بھیجے گئے',
    'recipients': 'صارفین کو',
    'Antigravity Agent 6 · executed': 'اینٹی گریویٹی ایجنٹ 6 · مکمل ہو گیا',
    'Executed': 'مکمل ہو گیا',
    'To:': 'کو:',
    'customers': 'صارفین',
    'SMS draft copied': 'ایس ایم ایس کا مسودہ کاپی ہو گیا',
    'Complete': 'مکمل',
    'state changes': 'حالت تبدیلیاں',
    'users reached': 'صارفین تک پہنچا',
    'errors': 'غلطیاں',
    's': 'سیکنڈ',
    'No delivery data': 'ڈیلیوری کا کوئی ڈیٹا نہیں',
    'Delivery report will appear after execution.': 'ڈیلیوری کی رپورٹ عملدرآمد کے بعد ظاہر ہوگی۔',
    'Notification delivery': 'نوٹیفکیشن کی ڈیلیوری',
    'SMS': 'ایس ایم ایس',
    'Email': 'ای میل',
    'Push': 'پش نوٹیفکیشن',
    'Skipped': 'چھوڑ دیا گیا',
    'Delivered to': 'تک پہنچایا گیا',
    'users': 'صارفین',
    'Off': 'بند',
    'Sent': 'بھیج دیا گیا',
    'Status:': 'حالت:',
    'total notifications': 'کل نوٹیفکیشنز',
    'Execution log': 'ایگزیکیوشن لاگ',
    'Orchestrated by Google Antigravity · Full workplan + task logs available for judge review': 'گوگل اینٹی گریویٹی کے زیر انتظام · جج کے جائزے کے لیے مکمل ورک پلان اور ٹاسک لاگز دستیاب ہیں',
    'Market': 'مارکیٹ',
    'Executions': 'عملدرآمد',
    'Mark all read': 'تمام پڑھے ہوئے نشان زد کریں',
    'No market alerts': 'کوئی مارکیٹ الرٹس نہیں ہیں',
    'No high-urgency feed items right now.': 'اس وقت کوئی اہم فیڈ آئٹمز موجود نہیں ہیں۔',
    'No execution alerts': 'کوئی عملدرآمد الرٹس نہیں ہیں',
    'When you execute an action, results appear here and as push notifications.': 'جب آپ کسی اقدام پر عملدرآمد کریں گے، تو نتائج یہاں اور پش نوٹیفکیشنز کے طور پر ظاہر ہوں گے۔',
    'New': 'نیا',
    'Execution alert': 'عملدرآمد الرٹ',
    'Skipped (disabled or missing contact)': 'چھوڑ دیا گیا (بند ہے یا رابطہ غائب ہے)',
    'Delivered': 'ڈیلیور ہو گیا',
    'View full result': 'مکمل نتیجہ دیکھیں',
    'Pakistan\'s Premier AI Business Intelligence & Action Advisor': 'پاکستان کا پہلا اے آئی بزنس انٹیلیجنس اور ایکشن ایڈوائزر',
    'Continue as Guest': 'مہمان کے طور پر جاری رکھیں',
    'TadbeerAI v1.0.0 · Built for AISeekho2026': 'تدبیر اے آئی v1.0.0 · AISeekho2026 کے لیے تیار کردہ',
    'Create your advisor account': 'اپنا ایڈوائزر اکاؤنٹ بنائیں',
    'Sign in to your account': 'اپنے اکاؤنٹ میں سائن ان کریں',
    'Valid email required': 'درست ای میل درکار ہے',
    'Phone number (e.g. +923001234567)': 'فون نمبر (مثلاً +923001234567)',
    'Phone number required': 'فون نمبر درکار ہے',
    'Enter valid Pakistan phone number (+923xxxxxxxxx)': 'درست پاکستانی فون نمبر درج کریں (+923xxxxxxxxx)',
    'Password must be at least 6 characters': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    'Sign in with Google': 'گوگل کے ساتھ سائن ان کریں',
    'Already have an account? Sign in': 'پہلے سے ہی ایک اکاؤنٹ ہے؟ سائن ان کریں',
    'New here? Create an account': 'یہاں نئے ہیں؟ اکاؤنٹ بنائیں',
    'Account mode enables automated email, SMS, and push notification alerts from TadbeerAI.': 'اکاؤنٹ موڈ تدبیر اے آئی سے خودکار ای میل، ایس ایم ایس، اور پش نوٹیفکیشن الرٹس کو فعال کرتا ہے۔',
    'Shop Information': 'دکان کی معلومات',
    'Business Information': 'کاروبار کی معلومات',
    'Employee Information': 'ملازم کی معلومات',
    'Student Information': 'طالب علم کی معلومات',
    'Complete details below to analyze your specific business risk and action recommendations.': 'اپنے مخصوص کاروباری خطرے اور کارروائی کی سفارشات کا تجزیہ کرنے کے لیے نیچے دی گئی تفصیلات مکمل کریں۔',
    'Shop Type (e.g. Grocery, Retail)': 'دکان کی قسم (مثلاً گروسری، ریٹیل)',
    'Monthly Revenue (PKR)': 'ماہانہ آمدنی (روپے)',
    'Inventory Size (Items Count)': 'انوینٹری کا سائز (اشیاء کی تعداد)',
    'Industry (e.g. IT, Manufacturing)': 'صنعت (مثلاً آئی ٹی، مینوفیکچرنگ)',
    'Monthly Turnover (PKR)': 'ماہانہ کاروبار (روپے)',
    'Employee Count': 'ملازمین کی تعداد',
    'Monthly Salary Range (PKR)': 'ماہانہ تنخواہ کی حد (روپے)',
    'Sector (e.g. Private, Public)': 'شعبہ (مثلاً پرائیویٹ، پبلک)',
    'Company Size (Employees)': 'کمپنی کا سائز (ملازمین)',
    'University Name': 'یونیورسٹی کا نام',
    'Field of Study (e.g. CS, Eng)': 'شعبہ تعلیم (مثلاً کمپیوٹر سائنس، انجینئرنگ)',
    'Monthly Stipend (PKR)': 'ماہانہ وظیفہ (روپے)',
    'This field is required': 'یہ خانہ پُر کرنا لازمی ہے',
    'Save & Proceed': 'محفوظ کریں اور آگے بڑھیں',
    'Churn risk: ': 'شرح نقصان: ',
    'Content ingestor': 'مواد حاصل کرنے والا ایجنٹ',
    'Insight extractor': 'معلومات نکالنے والا ایجنٹ',
    'Impact analyzer': 'اثرات کا تجزیہ کرنے والا ایجنٹ',
    'Action generator': 'اقدامات تجویز کرنے والا ایجنٹ',
    'Simulation agent': 'سیمولیشن ایجنٹ',
  };

  static String translate(String text) {
    return _urduTranslations[text] ?? text;
  }
}

extension TranslationExtension on String {
  String tr(BuildContext context) {
    final lang = Provider.of<LanguageProvider>(context);
    if (!lang.isUrdu) return this;
    return LanguageProvider.translate(this);
  }
}
